# -*- coding: utf-8 -*-
"""programa2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypxvzv-8jY08hi_fzgOEN8jnP3bl_MJZ
"""

!cp /content/drive/MyDrive/tecnicasdeprogramacionUnidad3/consolidado02/ejerciocio4/MiLibreria/libreria2.py /content/

#ahora importar
import libreria2

libreria2.funcionResta(12, 6)