# -*- coding: utf-8 -*-
"""programa3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6gIdvrWAFEafORPZ4o5KxcGkCKt8Fan
"""

!cp /content/drive/MyDrive/tecnicasdeprogramacionUnidad3/consolidado02/ejerciocio4/MiLibreria/libreria3.py /content/

#ahora importamos
import libreria3

libreria3.funcionMultiplicacion(9, 8)