# -*- coding: utf-8 -*-
"""Programa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMISJoUs2mENbqhBXS_YyhmfMvzLk86p
"""

# Haciendo......., se a conectar de  la siguinet anera:

!cp /content/drive/MyDrive/ejercicio1/Libreria/libreria.py /content/

# Ahora importar
import libreria

libreria.funcionSuma(4,5)