# -*- coding: utf-8 -*-
"""programa4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UovMe2caPEqtmTb4tbpBaHKxy2JkJKT
"""

!cp /content/drive/MyDrive/tecnicasdeprogramacionUnidad3/consolidado02/ejerciocio4/MiLibreria/libreria4.py /content/

import libreria4

libreria4.funcionDivision(12,2)